default: &default
  primary:
    username: root
    password:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: 127.0.0.1
  primary_replica:
    username: root
    password:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: 127.0.0.1
    replica: true

development: 
  <<: *default

test: 
  <<: *default

production: 
  <<: *default
