default: &default
  primary:
    database: <%= ENV["MYSQL_DATABASE"] %>
    username: <%= ENV["MYSQL_USERNAME"] %>
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_ADDRESS"] %>
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  primary_replica:
    database: <%= ENV["MYSQL_DATABASE"] %>
    username: <%= ENV["MYSQL_USERNAME"] %>
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_ADDRESS"] %>
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    replica: true
development: 
  <<: *default
test: 
  <<: *default
production: 
  <<: *default
