default: &default
  primary:
    database: <%= MYSQL_DATABASE %>
    username: <%= MYSQL_USERNAME %>
    password: <%= MYSQL_PASSWORD %>
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  primary_replica:
    database: <%= MYSQL_DATABASE %>
    username: <%= MYSQL_USERNAME %>
    password: <%= MYSQL_PASSWORD %>
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    replica: true
development: 
  <<: *default
test: 
  <<: *default
production: 
  <<: *default
